#!/usr/bin/env python
import sys
from rqt_gui.main import Main
from rqt_graphprofiler.visualizer_plugin import VisualizerPlugin

main = Main()
sys.exit(main.main(sys.argv, standalone='rqt_graphprofiler.visualizer_plugin.VisualizerPlugin', plugin_argument_provider=VisualizerPlugin.add_arguments))
